name: Generate documentation for nix options

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  generate_docs:
    runs-on: nix
    steps:
      - uses: actions/checkout@v5

      - name: Generate options file
        run: nix run github:Thunderbottom/nix-options-doc -- --format markdown --strip-prefix options. options.md

      - name: Create Pull Request
        uses: https://github.com/maxking/forgejo-create-pr@v2.12
        with:
          # required
          token: ${{ secrets.GH_TOKEN }}
          # optional
          base: 'main'
          commit-message: 'ci: update options documentation'
          pr-title: 'ci: update options documentation'
          pr-body: 'Updates the options.md documentation (automagic PR)'
          pr-condition-cmd: 'git status --porcelain'
